export default dummy = [
    {
        "address": "Australia Wollongong",
        "age": 24,
        "city": "Wollongong",
        "country": "Australia",
        "email": "amber.anderson@example.com",
        "gender": "female",
        "id": "003b32f8-a6d8-470c-b8f8-daf24befddb3",
        "img": {
            "large": "https://randomuser.me/api/portraits/women/28.jpg",
            "medium": "https://randomuser.me/api/portraits/med/women/28.jpg",
            "small": "https://randomuser.me/api/portraits/thumb/women/28.jpg",
        },
        "name": "Amber Anderson",
        "nationality": "AU",
        "phone": "0437-563-683",
        "title": "Miss",
        "username": "orangeswan704",
    },
    {
        "address": "United Kingdom Worcester",
        "age": 42,
        "city": "Worcester",
        "country": "United Kingdom",
        "email": "lola.johnson@example.com",
        "gender": "female",
        "id": "6c895ad5-d83c-42c8-8638-aa703dafb515",
        "img": {
            "large": "https://randomuser.me/api/portraits/women/15.jpg",
            "medium": "https://randomuser.me/api/portraits/med/women/15.jpg",
            "small": "https://randomuser.me/api/portraits/thumb/women/15.jpg",
        },
        "name": "Lola Johnson",
        "nationality": "GB",
        "phone": "0798-462-396",
        "title": "Miss",
        "username": "crazyswan986",
    },
    {
        "address": "France Rouen",
        "age": 27,
        "city": "Rouen",
        "country": "France",
        "email": "elisa.sanchez@example.com",
        "gender": "female",
        "id": "7e2834ef-9b21-47ea-936f-f24834e2c09f",
        "img": {
            "large": "https://randomuser.me/api/portraits/women/51.jpg",
            "medium": "https://randomuser.me/api/portraits/med/women/51.jpg",
            "small": "https://randomuser.me/api/portraits/thumb/women/51.jpg",
        },
        "name": "Elisa Sanchez",
        "nationality": "FR",
        "phone": "06-07-77-03-82",
        "title": "Miss",
        "username": "crazydog730",
    },
    {
        "address": "Norway Vossevangen",
        "age": 65,
        "city": "Vossevangen",
        "country": "Norway",
        "email": "zakaria.asheim@example.com",
        "gender": "male",
        "id": "489ba989-3b88-467e-a550-1e660765639e",
        "img": {
            "large": "https://randomuser.me/api/portraits/men/69.jpg",
            "medium": "https://randomuser.me/api/portraits/med/men/69.jpg",
            "small": "https://randomuser.me/api/portraits/thumb/men/69.jpg",
        },
        "name": "Zakaria Asheim",
        "nationality": "NO",
        "phone": "43279935",
        "title": "Mr",
        "username": "organicsnake738",
    },
    {
        "address": "Netherlands Oosterbierum",
        "age": 62,
        "city": "Oosterbierum",
        "country": "Netherlands",
        "email": "mariah.vanstigt@example.com",
        "gender": "female",
        "id": "bba79-907b-45c9-bc3e-64138342fd21",
        "img": {
            "large": "https://randomuser.me/api/portraits/women/50.jpg",
            "medium": "https://randomuser.me/api/portraits/med/women/50.jpg",
            "small": "https://randomuser.me/api/portraits/thumb/women/50.jpg",
        },
        "name": "Mariah Van Stigt",
        "nationality": "NL",
        "phone": "(834)-408-7863",
        "title": "Mrs",
        "username": "lazyswan694",
    },
    {
        "address": "Netherlands Oosterbierum",
        "age": 62,
        "city": "Oosterbierum",
        "country": "Netherlands",
        "email": "mariah.vanstigt@example.com",
        "gender": "female",
        "id": "bba74639-907b-45c9-be-64138342fd21",
        "img": {
            "large": "https://randomuser.me/api/portraits/women/35.jpg",
            "medium": "https://randomuser.me/api/portraits/med/women/35.jpg",
            "small": "https://randomuser.me/api/portraits/thumb/women/35.jpg",
        },
        "name": "Mariah Van Stigt",
        "nationality": "NL",
        "phone": "(834)-408-7863",
        "title": "Mrs",
        "username": "lazyswan694",
    },
    {
        "address": "Netherlands Oosterbierum",
        "age": 62,
        "city": "Oosterbierum",
        "country": "Netherlands",
        "email": "mariah.vanstigt@example.com",
        "gender": "female",
        "id": "bba74639-907b-4c9-bc3e-64138342fd21",
        "img": {
            "large": "https://randomuser.me/api/portraits/women/0.jpg",
            "medium": "https://randomuser.me/api/portraits/med/women/0.jpg",
            "small": "https://randomuser.me/api/portraits/thumb/women/0.jpg",
        },
        "name": "Mariah Van Stigt",
        "nationality": "NL",
        "phone": "(834)-408-7863",
        "title": "Mrs",
        "username": "lazyswan694",
    },
    {
        "address": "Netherlands Oosterbierum",
        "age": 62,
        "city": "Oosterbierum",
        "country": "Netherlands",
        "email": "mariah.vanstigt@example.com",
        "gender": "female",
        "id": "bba74639-907b-45c9-bc3e-6413834fd21",
        "img": {
            "large": "https://randomuser.me/api/portraits/women/10.jpg",
            "medium": "https://randomuser.me/api/portraits/med/women/10.jpg",
            "small": "https://randomuser.me/api/portraits/thumb/women/10.jpg",
        },
        "name": "Mariah Van Stigt",
        "nationality": "NL",
        "phone": "(834)-408-7863",
        "title": "Mrs",
        "username": "lazyswan694",
    },
]